blank_issues_enabled: true
contact_links:
  - name: Support discussion
    url: https://github.com/Sigmapitech/glados/discussions/categories/help
    about: Start here for general questions and help
  - name: Documentation
    url: https://glados.1l.is/
    about: Check out the documentation for guides and specifications
  - name: Report a bug
    url: https://github.com/Sigmapitech/glados/discussions/categories/bug-report
    about: Report a bug or unexpected behavior
